services:
  - type: web
    name: jirasecondprime
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --timeout 180 --bind 0.0.0.0:$PORT
   

    envVars:
      - key: PORT
        value: 10000
      - key: JIRA_BASE_URL
        value: amaniconsulting.atlassian.net
      - key: JIRA_EMAIL
        value: hermann.glan@amani.consulting
      - key: JIRA_PROJECT_KEY
        value: ACD
      - key: LM_STUDIO_BASE_URL
        value: https://concentrations-strange-achieve-w.trycloudflare.com/v1/models
      - key: JIRA_API_TOKEN
        sync: false  # Vous devrez ajouter cette variable manuellement dans l'interface Render