services:
  - type: web
    name: jirasecondprime
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
        key: API_URL
        value: https://abraham-certification-memories-cl.trycloudflare.com/v1/chat/completions
    autoDeploy: true